import { render, screen, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";

import { AffiliateMoney } from "@/components/workspace/live/affiliate-money";
import { WorkspaceEnvProvider } from "@/components/workspace/workspace-env";

vi.mock("next/navigation", () => ({
  useRouter: () => ({ refresh: vi.fn() }),
}));

const referrals = [
  { accountStatus: "paying" as const, businessName: "Northstar Coaching", commissionEarnedCents: 1_250 },
  { accountStatus: "cancelled" as const, businessName: "Northstar Coaching", commissionEarnedCents: 750 },
];
const payouts = [{
  amountCents: 1_000,
  recordedOn: "2026-08-20",
  reference: "synthetic-reference",
  state: "sent" as const,
}];

afterEach(() => {
  vi.unstubAllGlobals();
});

describe("AffiliateMoney", () => {
  it("suppresses unconfirmed totals and tables during the first load", () => {
    vi.stubGlobal("fetch", vi.fn(() => new Promise<Response>(() => {})));

    render(<AffiliateMoney enabled termsCopy={null} />);

    expect(screen.getByRole("main", { name: "Loading content" })).toBeVisible();
    expect(screen.queryByText("No earned commission yet")).not.toBeInTheDocument();
    expect(screen.queryByText("No payout has been sent")).not.toBeInTheDocument();
    expect(screen.queryByRole("region", { name: "Referred coaches" })).not.toBeInTheDocument();
  });

  it("suppresses stale totals and tables after a load failure", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => new Response(JSON.stringify({ error: "Unavailable" }), {
      headers: { "Content-Type": "application/json" },
      status: 503,
    })));

    render(<AffiliateMoney enabled termsCopy={null} />);

    expect(await screen.findByText("Partner earnings could not load")).toBeVisible();
    expect(screen.queryByText("No earned commission yet")).not.toBeInTheDocument();
    expect(screen.queryByText("No payout has been sent")).not.toBeInTheDocument();
    expect(screen.queryByRole("region", { name: "Referred coaches" })).not.toBeInTheDocument();
  });

  it("keeps duplicate business names as separate rows and exports populated payout history", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => new Response(JSON.stringify({ referrals, payouts }), {
      headers: { "Content-Type": "application/json" },
      status: 200,
    })));

    render(
      <AffiliateMoney
        enabled
        initialPayouts={payouts}
        initialReferrals={referrals}
        termsCopy={null}
      />,
    );

    expect(screen.getAllByText("Northstar Coaching")).toHaveLength(2);
    expect(screen.getByText("Total")).toBeVisible();
    expect(screen.getAllByText("$20.00").length).toBeGreaterThan(0);
    expect(
      screen.getAllByRole("region", { name: "Payout history" })
        .some((element) => element.tagName === "DIV" && element.querySelector("table")),
    ).toBe(true);
    expect(screen.getAllByRole("button", { name: "Export table" })).toHaveLength(2);
  });

  it("offers both the link and the code, now that signup reads the parameter", async () => {
    // This test used to pin the opposite. The link was generated by the route and read by nothing,
    // so copying it dropped the affiliate's commission in silence; the refusal stood until
    // `src/app/signup/page.tsx` read `?ref=` and prefilled the field. The biconditional in
    // `src/lib/affiliates/referral-attribution.test.ts` is what stops the two halves drifting
    // apart again; this asserts the half a person can see.
    vi.stubGlobal("fetch", vi.fn(async () => new Response(
      JSON.stringify({ payouts, referral: { code: "SF-A1B2C3D4E5F6", link: "https://setterfi.test/signup?ref=SF-A1B2C3D4E5F6" }, referrals }),
      { headers: { "Content-Type": "application/json" }, status: 200 },
    )));

    render(<AffiliateMoney enabled termsCopy={null} />);

    expect(await screen.findByText("https://setterfi.test/signup?ref=SF-A1B2C3D4E5F6")).toBeVisible();
    expect(screen.getByRole("button", { name: "Copy referral link" })).toBeVisible();
    // The code stays: an affiliate on a call reads out a code, not a URL.
    expect(screen.getByText("SF-A1B2C3D4E5F6")).toBeVisible();
    expect(screen.getByRole("button", { name: "Copy referral code" })).toBeVisible();
  });

  it("falls back to the code alone when the link would attribute nothing", async () => {
    // A link whose parameter has gone missing looks exactly like one that works, and the person it
    // fails is the affiliate, who finds out by never being paid. The code always works, so the
    // degraded state is the honest one rather than an error.
    vi.stubGlobal("fetch", vi.fn(async () => new Response(
      JSON.stringify({ payouts, referral: { code: "SF-A1B2C3D4E5F6", link: "https://setterfi.test/signup" }, referrals }),
      { headers: { "Content-Type": "application/json" }, status: 200 },
    )));

    render(<AffiliateMoney enabled termsCopy={null} />);

    expect(await screen.findByText("SF-A1B2C3D4E5F6")).toBeVisible();
    expect(screen.getByRole("button", { name: "Copy referral code" })).toBeVisible();
    expect(screen.queryByRole("button", { name: "Copy referral link" })).not.toBeInTheDocument();
    expect(screen.queryByText("https://setterfi.test/signup")).not.toBeInTheDocument();
  });

  it("reports earned, paid out and payable, and says what the payable figure is made of", async () => {
    // Earned 20.00 across two referrals, 10.00 sent, 6.00 approved and waiting. Payable is derived
    // as earned minus sent rather than summed from payout states, because commission that has
    // never been approved belongs to no payout and would otherwise vanish from the affiliate's
    // own balance.
    vi.stubGlobal("fetch", vi.fn(async () => new Response(
      JSON.stringify({
        payouts: [
          ...payouts,
          { amountCents: 600, recordedOn: null, reference: null, state: "approved_for_payout" },
        ],
        referral: { code: "SF-A1B2C3D4E5F6", link: "https://x" },
        referrals,
      }),
      { headers: { "Content-Type": "application/json" }, status: 200 },
    )));

    render(<AffiliateMoney enabled termsCopy={null} />);

    /*
     * Scoped by the panel's own section rather than by `parentElement`.
     *
     * The three figures used to be a `FigureStrip`, whose tile put the label and the figure under
     * one parent, so `getByText(label).parentElement` was the tile. They are deck panels now, and a
     * deck panel's name lives in the header band while its figure lives in the body -- the two are
     * siblings' children, not one parent's. Walking to the panel's `<section>` is what survives
     * that, and it is also the truer assertion: the panel is the thing labelled "Payable", so the
     * figure and the note being *inside it* is the claim worth pinning. `DeckPanel` renders the
     * name as the heading, so this drifts red rather than green if the anatomy moves again.
     */
    const summary = within(await screen.findByLabelText("Earnings summary"));
    const tile = (label: string) =>
      within(summary.getByText(label).closest("section") as HTMLElement);
    expect(tile("Earned, all time").getByText("$20.00")).toBeVisible();
    expect(tile("Paid out").getByText("$10.00")).toBeVisible();
    // Earned minus sent, not the approved sum: the 6.00 approved is only part of what is owed.
    expect(tile("Payable").getByText("$10.00")).toBeVisible();
    expect(tile("Payable").getByText("$6.00 approved, waiting on the bank")).toBeVisible();
    // An approved payout has no reference because none exists yet, which is one absence rather
    // than two empty cells.
    expect(
      screen.getByText("not sent yet, so no reference exists"),
    ).toBeVisible();
  });
  it("labels the copy control in words rather than with a glyph alone", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => new Response(
      JSON.stringify({ payouts, referral: { code: "SF-A1B2C3D4E5F6", link: "https://setterfi.test/signup?ref=SF-A1B2C3D4E5F6" }, referrals }),
      { headers: { "Content-Type": "application/json" }, status: 200 },
    )));

    render(<AffiliateMoney enabled termsCopy={null} />);

    // Visible text, not only an aria-label and not a screen-reader-only span: this surface is
    // built for readers who do not necessarily recognise the clipboard glyph, and it is the one
    // control the page exists for. `toHaveTextContent` cannot tell the two apart -- jsdom counts
    // an `sr-only` child as text content -- so this asserts a text node the button renders
    // directly, which an `sr-only` wrapper would not produce.
    const visibleLabel = (button: HTMLElement) =>
      Array.from(button.childNodes)
        .filter((node) => node.nodeType === Node.TEXT_NODE)
        .map((node) => node.textContent ?? "")
        .join("")
        .trim();

    const copyLink = await screen.findByRole("button", { name: "Copy referral link" });
    expect(visibleLabel(copyLink)).toBe("Copy referral link");
    expect(visibleLabel(screen.getByRole("button", { name: "Copy referral code" })))
      .toBe("Copy referral code");
  });

  it("states the real referral count once it has one, and never before", async () => {
    const NEUTRAL = "Coaches who signed up through your code";

    // In flight. An empty `referrals` array is not evidence that nobody has signed up -- it is the
    // state before anything is known -- so the head must make no claim about the count at all.
    vi.stubGlobal("fetch", vi.fn(() => new Promise<Response>(() => {})));
    const pending = render(<AffiliateMoney enabled termsCopy={null} />);
    const headText = (view: { container: HTMLElement }) =>
      view.container.querySelector("[data-page-head=\"affiliate\"]")?.textContent ?? "";
    expect(headText(pending)).toContain(NEUTRAL);
    pending.unmount();

    // Failed. Same reasoning, and the failure is the case a count is most likely to leak from.
    vi.unstubAllGlobals();
    vi.stubGlobal("fetch", vi.fn(async () => new Response(JSON.stringify({ error: "Unavailable" }), {
      headers: { "Content-Type": "application/json" },
      status: 503,
    })));
    const failed = render(<AffiliateMoney enabled termsCopy={null} />);
    await screen.findByText("Partner earnings could not load");
    expect(headText(failed)).toContain(NEUTRAL);
    failed.unmount();

    vi.unstubAllGlobals();
    vi.stubGlobal("fetch", vi.fn(async () => new Response(
      JSON.stringify({ payouts, referral: { code: "SF-A1B2C3D4E5F6", link: "https://setterfi.test/signup?ref=SF-A1B2C3D4E5F6" }, referrals }),
      { headers: { "Content-Type": "application/json" }, status: 200 },
    )));
    const loaded = render(<AffiliateMoney enabled termsCopy={null} />);
    await screen.findByText("SF-A1B2C3D4E5F6");
    expect(loaded.container.querySelector("[data-page-head=\"affiliate\"]")?.textContent)
      .toContain("2 coaches have signed up through your link");
  });

  /**
   * The four states, and the one that matters most is the one that used to be invisible.
   *
   * "Active"/"Inactive" merged a coach mid-setup with a cancelled one, and counted a coach whose
   * payments had stalled as active -- telling the affiliate money was still coming from an account
   * that had stopped paying for it. The negative assertion is the load-bearing half: neither old
   * label may survive anywhere on the table.
   */
  it("tells the four referral states apart, and never reads a stalled account as paying", async () => {
    const fourStates = [
      { accountStatus: "setting_up" as const, businessName: "Aster Credit", commissionEarnedCents: 0 },
      { accountStatus: "paying" as const, businessName: "Beacon Funding", commissionEarnedCents: 4_500 },
      { accountStatus: "payment_problem" as const, businessName: "Cedar Capital", commissionEarnedCents: 2_000 },
      { accountStatus: "cancelled" as const, businessName: "Dunmore Coaching", commissionEarnedCents: 900 },
    ];
    vi.stubGlobal("fetch", vi.fn(async () => new Response(
      JSON.stringify({ payouts, referral: { code: "SF-A1B2C3D4E5F6", link: "https://setterfi.test/signup?ref=SF-A1B2C3D4E5F6" }, referrals: fourStates }),
      { headers: { "Content-Type": "application/json" }, status: 200 },
    )));

    const view = render(<AffiliateMoney enabled termsCopy={null} />);
    await screen.findAllByText("SF-A1B2C3D4E5F6");
    // The section, not the scroller inside it: `DataTable` labels its own scroll region with the
    // same string, so the role query matches two elements and the outer one is the whole table.
    const table = view.container.querySelector("[aria-labelledby=\"referrals-heading\"]")!;

    expect(within(table as HTMLElement).getByText("Still setting up")).toBeVisible();
    expect(within(table as HTMLElement).getByText("Paying")).toBeVisible();
    expect(within(table as HTMLElement).getByText("Payment problem")).toBeVisible();
    expect(within(table as HTMLElement).getByText("Cancelled")).toBeVisible();

    // The two labels this change exists to retire, and the claim they used to make.
    expect(table.textContent).not.toMatch(/\bActive\b/u);
    expect(table.textContent).not.toMatch(/\bInactive\b/u);
    // A stalled account is not paying, and the row says so rather than staying silent.
    expect(within(table as HTMLElement).getByText("no new commission accrues while this is unresolved")).toBeVisible();
  });

  /**
   * The greeting is the signed-in row or it is nothing. Both halves are asserted in one test,
   * because the fallback is the half that protects the honesty rule -- a head that greets
   * "Welcome back," with an empty space, or worse a stand-in name, is the failure this page
   * spent two rounds refusing to ship.
   */
  it("greets the affiliate by the name the layout resolved, and by no name when it resolved none", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => new Response(
      JSON.stringify({ payouts, referral: { code: "SF-A1B2C3D4E5F6", link: "https://setterfi.test/signup?ref=SF-A1B2C3D4E5F6" }, referrals }),
      { headers: { "Content-Type": "application/json" }, status: 200 },
    )));

    const named = render(
      <WorkspaceEnvProvider
        account={{ business: "Northstar Coaching", firstName: "Dana", fullName: "Dana Whitfield" }}
        demoAccountSwitching={false}
        demoViews={[]}
        mode="supabase"
      >
        <AffiliateMoney enabled termsCopy={null} />
      </WorkspaceEnvProvider>,
    );
    await screen.findAllByText("SF-A1B2C3D4E5F6");
    expect(named.container.querySelector("[data-page-head=\"affiliate\"] h1")?.textContent)
      .toBe("Welcome back, Dana");
    named.unmount();

    // No provider at all is the same shape as "the layout resolved nothing": undefined account.
    const anonymous = render(<AffiliateMoney enabled termsCopy={null} />);
    await screen.findAllByText("SF-A1B2C3D4E5F6");
    const head = anonymous.container.querySelector("[data-page-head=\"affiliate\"] h1")?.textContent ?? "";
    expect(head).toBe("Your referrals");
    expect(head).not.toMatch(/welcome back/iu);
  });

  it("says nothing has happened yet rather than showing a bare zero", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => new Response(
      JSON.stringify({ payouts: [], referral: { code: "SF-A1B2C3D4E5F6", link: "https://setterfi.test/signup?ref=SF-A1B2C3D4E5F6" }, referrals: [] }),
      { headers: { "Content-Type": "application/json" }, status: 200 },
    )));

    const view = render(<AffiliateMoney enabled termsCopy={null} />);
    await screen.findByText("SF-A1B2C3D4E5F6");
    const head = view.container.querySelector("[data-page-head=\"affiliate\"]")?.textContent ?? "";
    expect(head).toContain("Nobody has signed up through your link yet");
    expect(head).not.toMatch(/\b0 coaches\b/);
  });
});
