/** The exact coach-writable offer keys, shared by every route that accepts an offer body. */
export const COACH_OFFER_KEYS = [
  "assets",
  "bookingHorizonDays",
  "bookingMode",
  "brandVoice",
  "cadencePurposes",
  "creditMin",
  "creditRepair",
  "fundingGoalMaxCents",
  "fundingGoalMinCents",
  "monthlyRevenueMinCents",
  "prices",
  "products",
  "programDescription",
  "programName",
  "proof",
  "refundPosture",
  "resultsTimelineMaxDays",
  "resultsTimelineMinDays",
  "voiceFollowupAnswer",
  "voiceObjectionAnswer",
  "voiceStyleAnswer",
] as const;
